# Generated by Django 3.0.2 on 2020-01-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0005_auto_20200130_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinfo',
            name='isavail',
            field=models.IntegerField(choices=[(0, 'YES'), (1, 'NO')]),
        ),
    ]
