# Generated by Django 3.0.2 on 2020-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0006_auto_20200130_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorinfo',
            name='domain',
            field=models.IntegerField(choices=[(1, 'Primary Health Care'), (2, 'Pediatric Clinic'), (3, 'Gynaecological Clinic'), (4, 'Outpatient Surgery')], default=0),
            preserve_default=False,
        ),
    ]
