# Generated by Django 3.0.3 on 2020-02-13 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_name', models.CharField(max_length=200)),
                ('D_username', models.CharField(max_length=200, unique=True)),
                ('D_email', models.EmailField(max_length=254, unique=True)),
                ('domain', models.IntegerField(choices=[(1, 'Primary Health Care'), (2, 'Pediatric Clinic'), (3, 'Gynaecological Clinic'), (4, 'Pediatric Clinic')])),
                ('isavail', models.IntegerField(choices=[(0, 'NO'), (1, 'YES')])),
            ],
        ),
        migrations.AddField(
            model_name='patientregstration',
            name='actualtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregstration',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregstration',
            name='isinqueue',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregstration',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientregstration',
            name='predictedtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientregstration',
            name='patient_type',
            field=models.IntegerField(choices=[(1, 'Diagonistics'), (2, 'Followup'), (3, 'Prevention'), (4, 'Emergency')]),
        ),
        migrations.AddField(
            model_name='patientregstration',
            name='DoctorInfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home1.DoctorInfo'),
        ),
    ]
