# Generated by Django 2.2.7 on 2020-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregstration',
            name='age',
            field=models.IntegerField(),
        ),
    ]
