# Generated by Django 3.0.3 on 2020-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0002_auto_20200213_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregstration',
            name='number',
            field=models.CharField(max_length=200),
        ),
    ]
