# Generated by Django 3.0.2 on 2020-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0003_auto_20200130_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientregstration',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Diagonistics'), (2, 'Followup'), (3, 'Prevention'), (4, 'Emergency')]),
        ),
        migrations.AlterField(
            model_name='patientregstration',
            name='patient_type',
            field=models.IntegerField(choices=[(1, 'Diagonistics'), (2, 'Followup'), (3, 'Prevention'), (4, 'Emergency')]),
        ),
    ]
